changelog_type: 'pull_request'
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
pull_request_title_regex: '(^.*[0-9]{1,2}[.]+[0-9]{1,2})'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'