name: CI

on:
  push:
    paths:
      - Dockerfile
      - build.sh
  pull_request:
    paths:
      - Dockerfile
      - build.sh
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build deb
        run: |
          mkdir build
          bash build.sh

      - name: Store archives
        uses: actions/upload-artifact@v3
        with:
          name: snapraid-deb
          path: build/*.deb
          if-no-files-found: error

      # delete-artifact
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: snapraid-deb
