name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build deb
        run: bash build.sh

      - name: Store archives
        uses: actions/upload-artifact@v2
        with:
          name: snapraid-deb
          path: build/*.deb
          if-no-files-found: error
