name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deb
        run: bash build.sh

      # - name: CreateRelease
        # uses: ncipollo/release-action@v1
        # with:
          # artifacts: "build/*.deb"
          # token: ${{ secrets.GITHUB_TOKEN }}
          # allowUpdates: true
          # artifactErrorsFailBuild: true
          # tag: "12.0"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.deb
          body_path: https://github.com/amadvance/snapraid/blob/master/HISTORY
          tag_name: vTest
          fail_on_unmatched_files: true