name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update HISTORY file
        id: update_file
        uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
        with:
          url: https://raw.githubusercontent.com/amadvance/snapraid/master/HISTORY
          file_in_repo: HISTORY

      - name: Build deb
        run: bash build.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          tag: "12.1"
          #body: "See Release notes: https://github.com/amadvance/snapraid/blob/master/HISTORY"
          bodyfile: HISTORY
